"""
Inference Script: Segment New LAZ Tiles with Trained SegFormer
=================================================================
Step 4 of the curb-gutter segmentation pipeline.

What this script does:
  1. Reads config.json from --model_folder (auto-generated by train_segformer.py)
  2. Loads best.pt using the SAME build_model() function training used
     (imported from model_arch.py — guaranteed architecture match)
  3. Rasterizes new unlabeled LAZ tiles using the SAME settings training used
     (resolution, k-neighbors — read from config.json, not re-typed)
  4. Runs sliding-window inference with logit-averaging in overlap regions
  5. Back-projects predictions to 3D: Option A — only the highest-z point per
     pixel gets the predicted label directly, then a nearest-neighbor pass
     fills the remaining points in 3D space
  6. Writes predictions into the LAZ `classification` field
  7. Saves a 2D segmentation PNG + an RGB-overlay PNG for visual QA

Usage (folder mode):
  python inference.py \\
    --model_folder /path/to/checkpoints/Test_Run1_512Patches/ \\
    --input_folder /path/to/new/unlabeled/laz/ \\
    --output_folder /path/to/segmented/output/

Usage (single file mode):
  python inference.py \\
    --model_folder /path/to/checkpoints/Test_Run1_512Patches/ \\
    --single_file /path/to/one_tile.laz \\
    --output_folder /path/to/segmented/output/

All settings (resolution, k, patch_size, channel order, model architecture)
are read automatically from config.json inside --model_folder. You do NOT
need to re-specify them — this is the whole point of the config system.

If --input_folder / --single_file / --output_folder are omitted, the script
falls back to the inference_config values stored in config.json, so you can
also just edit config.json by hand and run with only --model_folder.

Dependencies:
  pip install torch torchvision transformers
  pip install laspy lazrs-python numpy scikit-learn opencv-python tqdm
"""

import argparse
import os
import sys
import json
import numpy as np
from pathlib import Path
import cv2
import laspy

import torch
import torch.nn.functional as F

from model_arch import build_model, CHANNEL_ORDER

try:
    from tqdm import tqdm
except ImportError:
    def tqdm(x, **kwargs):
        return x


# ─── Reuse the exact rasterization logic from data prep ───────────────────
# These functions are intentionally identical to prepare_dataset.py.
# If you ever change rasterization there, mirror the change here too —
# or better, factor both into a shared module later.

def load_laz(path):
    try:
        import laspy
    except ImportError:
        print("ERROR: pip install laspy lazrs-python")
        sys.exit(1)
    return laspy.read(str(path))


def get_arrays(las):
    x = np.array(las.x, dtype=np.float64)
    y = np.array(las.y, dtype=np.float64)
    z = np.array(las.z, dtype=np.float64)

    intensity = None
    if hasattr(las, 'intensity'):
        intensity = np.array(las.intensity, dtype=np.float32)
        mx = intensity.max()
        if mx > 0:
            intensity /= mx

    rgb = None
    if all(hasattr(las, c) for c in ['red', 'green', 'blue']):
        r = np.array(las.red,   dtype=np.float32)
        g = np.array(las.green, dtype=np.float32)
        b = np.array(las.blue,  dtype=np.float32)
        mx = max(r.max(), g.max(), b.max())
        if mx > 0:
            r /= mx; g /= mx; b /= mx
        rgb = np.stack([r, g, b], axis=1)

    return x, y, z, intensity, rgb


def compute_verticality(x, y, z, k=25, batch_size=100_000):
    from sklearn.neighbors import KDTree

    pts = np.column_stack([x, y, z]).astype(np.float32)
    tree = KDTree(pts)
    _, indices = tree.query(pts, k=k + 1)
    indices = indices[:, 1:]

    n = len(pts)
    verticality = np.zeros(n, dtype=np.float32)

    for start in range(0, n, batch_size):
        end = min(start + batch_size, n)
        neighbors = pts[indices[start:end]]
        centroid  = neighbors.mean(axis=1, keepdims=True)
        centered  = neighbors - centroid
        cov = np.einsum('bki,bkj->bij', centered, centered) / k
        try:
            eigvals = np.linalg.eigvalsh(cov)
            lam0 = eigvals[:, 0]
            lam2 = eigvals[:, 2]
            denom = np.where(lam2 > 1e-9, lam2, 1e-9)
            verticality[start:end] = np.clip(lam0 / denom, 0, 1)
        except np.linalg.LinAlgError:
            pass

    return verticality


def compute_height_above_ground(x, y, z, cell_size=1.0):
    xi = np.floor((x - x.min()) / cell_size).astype(np.int32)
    yi = np.floor((y - y.min()) / cell_size).astype(np.int32)
    key = xi.astype(np.int64) * 100000 + yi.astype(np.int64)

    hag = np.zeros(len(z), dtype=np.float32)
    for uk in np.unique(key):
        mask = key == uk
        hag[mask] = z[mask] - z[mask].min()

    mx = hag.max()
    if mx > 0:
        hag /= mx
    return hag


def build_raster(x, y, z, intensity, rgb, verticality, hag, resolution):
    """
    Same as prepare_dataset.py's build_raster, minus label handling
    (we don't have labels here — we're predicting them).
    Returns raster (H, W, 6) float32, point_pixel_map (N,) int32 flat pixel
    index per point, and (x_min, y_min, rows, cols) meta.
    """
    x_min, y_min = x.min(), y.min()
    cols = int(np.ceil((x.max() - x_min) / resolution)) + 1
    rows = int(np.ceil((y.max() - y_min) / resolution)) + 1

    col_idx = np.floor((x - x_min) / resolution).astype(np.int32)
    row_idx = np.floor((y - y_min) / resolution).astype(np.int32)
    flat    = row_idx * cols + col_idx
    n_px    = rows * cols

    z_grid  = np.full(n_px, -np.inf, dtype=np.float32)
    winner  = np.full(n_px, -1,      dtype=np.int32)
    order   = np.argsort(z)
    for pt_i in order:
        fi = flat[pt_i]
        if 0 <= fi < n_px and z[pt_i] > z_grid[fi]:
            z_grid[fi] = z[pt_i]
            winner[fi] = pt_i

    valid_flat = np.where(winner >= 0)[0]
    valid_pts  = winner[valid_flat]
    ri = valid_flat // cols
    ci = valid_flat  % cols

    raster = np.zeros((rows, cols, 6), dtype=np.float32)
    raster[ri, ci, 0] = hag[valid_pts]
    raster[ri, ci, 1] = verticality[valid_pts]
    raster[ri, ci, 2] = intensity[valid_pts] if intensity is not None else 0.0
    if rgb is not None:
        raster[ri, ci, 3] = rgb[valid_pts, 0]
        raster[ri, ci, 4] = rgb[valid_pts, 1]
        raster[ri, ci, 5] = rgb[valid_pts, 2]

    # point_pixel_map: for EVERY point (not just winners), which flat pixel
    # index it falls into. Needed later for Option A back-projection.
    point_pixel_map = flat.astype(np.int64)

    return raster, winner, point_pixel_map, (x_min, y_min, rows, cols)


# ─── Sliding window inference ───────────────────────────────────────────

@torch.no_grad()
def run_sliding_inference(model, raster, patch_size, stride, device,
                          num_labels=3, batch_inf=4):
    """
    Slide a window over the full raster, run the model on each patch,
    accumulate logits into a full-size logit map with overlap-averaging.

    Returns: predicted_label_map (H, W) uint8
    """
    H, W = raster.shape[:2]

    # Pad raster so the sliding window always fits cleanly
    pad_h = max(0, patch_size - H)
    pad_w = max(0, patch_size - W)
    if pad_h > 0 or pad_w > 0:
        raster_padded = np.zeros((H + pad_h, W + pad_w, 6), dtype=np.float32)
        raster_padded[:H, :W] = raster
        raster = raster_padded
        H, W = raster.shape[:2]

    logit_accum = np.zeros((num_labels, H, W), dtype=np.float32)
    count_accum = np.zeros((H, W), dtype=np.float32)

    # Generate sliding window positions, ensuring full coverage including
    # the right/bottom edges even when stride doesn't evenly divide
    # (H - patch_size) or (W - patch_size).
    row_starts = list(range(0, H - patch_size + 1, stride))
    col_starts = list(range(0, W - patch_size + 1, stride))
    if row_starts[-1] != H - patch_size:
        row_starts.append(H - patch_size)
    if col_starts[-1] != W - patch_size:
        col_starts.append(W - patch_size)

    positions = [(r, c) for r in row_starts for c in col_starts]

    print(f"  Running inference on {len(positions)} patches...")

    batch_imgs, batch_pos = [], []
    for (r, c) in tqdm(positions, desc="  Inference"):
        patch = raster[r:r+patch_size, c:c+patch_size]  # (P, P, 6)

        # Skip patches that are entirely empty — saves compute, avoids
        # the model hallucinating structure on pure padding.
        if (patch[:, :, 0] > 0).sum() == 0:
            continue

        batch_imgs.append(patch)
        batch_pos.append((r, c))

        if len(batch_imgs) == batch_inf:
            _run_batch(model, batch_imgs, batch_pos, patch_size,
                      logit_accum, count_accum, device)
            batch_imgs, batch_pos = [], []

    if batch_imgs:
        _run_batch(model, batch_imgs, batch_pos, patch_size,
                  logit_accum, count_accum, device)

    # Average overlapping predictions
    count_safe = np.where(count_accum > 0, count_accum, 1)
    logit_accum = logit_accum / count_safe[None, :, :]

    pred = np.argmax(logit_accum, axis=0).astype(np.uint8)

    # Mask out pixels that had zero coverage (no patch touched them at all —
    # shouldn't happen given our position coverage, but defensive)
    pred[count_accum == 0] = 0  # unlabeled

    # Crop back to original size if we padded
    pred = pred[:H, :W]
    return pred


def _run_batch(model, batch_imgs, batch_pos, patch_size,
              logit_accum, count_accum, device):
    """Run one mini-batch through the model and accumulate logits."""
    imgs = np.stack(batch_imgs, axis=0)                      # (B, P, P, 6)
    imgs_t = torch.from_numpy(imgs.transpose(0, 3, 1, 2)).float().to(device)

    with torch.cuda.amp.autocast():
        outputs = model(pixel_values=imgs_t)
        logits  = outputs.logits  # (B, num_labels, P/4, P/4)
        logits_up = F.interpolate(
            logits, size=(patch_size, patch_size),
            mode='bilinear', align_corners=False)

    logits_np = logits_up.float().cpu().numpy()  # (B, num_labels, P, P)

    for i, (r, c) in enumerate(batch_pos):
        logit_accum[:, r:r+patch_size, c:c+patch_size] += logits_np[i]
        count_accum[r:r+patch_size, c:c+patch_size] += 1.0


# ─── Back-projection: Option A ──────────────────────────────────────────

def backproject_to_3d(pred_label_map, winner, point_pixel_map, x, y, z, cols):
    """
    Option A back-projection:
      1. Only the highest-z point per pixel (winner) gets the predicted
         label DIRECTLY from the 2D map.
      2. All other points get labeled via nearest-neighbor propagation
         in true 3D space from the labeled winner points.

    Returns: labels (N,) uint8 array, one label per input point.
    """
    n_points = len(x)
    labels = np.zeros(n_points, dtype=np.uint8)  # default: unlabeled

    H, W = pred_label_map.shape
    pred_flat = pred_label_map.flatten()  # indexed by row*cols + col, matching point_pixel_map convention

    # Step 1: assign winners directly
    valid_winners = winner[winner >= 0]
    if len(valid_winners) > 0:
        winner_pixel_flat = np.where(winner >= 0)[0]  # these ARE flat pixel indices
        # pred_flat is indexed by row*W + col; our raster used row*cols + col
        # during construction, and cols here must match W used in pred_label_map
        # (they do, since pred_label_map came from the same raster).
        valid_pixel_idx = winner_pixel_flat[winner_pixel_flat < len(pred_flat)]
        winner_point_idx = winner[valid_pixel_idx]
        labels[winner_point_idx] = pred_flat[valid_pixel_idx]

    print(f"  Directly labeled (winner points): {len(valid_winners):,} / {n_points:,}")

    # Step 2: nearest-neighbor propagate to the rest.
    # We track which points were DIRECTLY assigned via an explicit boolean
    # mask (not via labels > 0), since a winner point's predicted class
    # could itself legitimately be 0 (unlabeled) — that's still a direct
    # assignment, not a gap to fill.
    directly_labeled = np.zeros(n_points, dtype=bool)
    if len(valid_winners) > 0:
        directly_labeled[winner_point_idx] = True

    n_unlabeled = (~directly_labeled).sum()
    print(f"  Propagating to remaining {n_unlabeled:,} points via nearest-neighbor...")

    if n_unlabeled > 0 and directly_labeled.sum() > 0:
        from sklearn.neighbors import KDTree
        labeled_pts = np.column_stack([x[directly_labeled], y[directly_labeled], z[directly_labeled]])
        unlabeled_pts = np.column_stack([x[~directly_labeled], y[~directly_labeled], z[~directly_labeled]])

        tree = KDTree(labeled_pts)
        # Query in batches to bound memory on very large point counts
        batch_size = 500_000
        nn_labels = np.zeros(len(unlabeled_pts), dtype=np.uint8)
        labeled_label_values = labels[directly_labeled]

        for start in range(0, len(unlabeled_pts), batch_size):
            end = min(start + batch_size, len(unlabeled_pts))
            _, idx = tree.query(unlabeled_pts[start:end], k=1)
            nn_labels[start:end] = labeled_label_values[idx.flatten()]

        labels[~directly_labeled] = nn_labels

    return labels


# ─── Visualization ───────────────────────────────────────────────────────

def save_visualizations(raster, pred_label_map, output_dir, tile_name):

    os.makedirs(output_dir, exist_ok=True)

    label_colors = {
        0: [252, 3, 3],  # unlabeled - red
        1: [212, 190, 190],  # ground - black gray
        2: [10, 10, 10],     # road - gray
    }

    color_mask = np.zeros((*pred_label_map.shape, 3), dtype=np.uint8)
    for lbl, color in label_colors.items():
        color_mask[pred_label_map == lbl] = color

    seg_path = Path(output_dir) / f"{tile_name}_segmentation.png"
    cv2.imwrite(str(seg_path), color_mask)

    rgb = (raster[:, :, 3:6] * 255).astype(np.uint8)
    rgb_bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
    overlay = cv2.addWeighted(rgb_bgr, 0.6, color_mask, 0.4, 0)
    overlay_path = Path(output_dir) / f"{tile_name}_overlay.png"
    cv2.imwrite(str(overlay_path), overlay)

    print(f"  Saved: {seg_path.name}, {overlay_path.name}")


# ─── Single tile pipeline ───────────────────────────────────────────────

def get_or_compute_verticality(las, x, y, z, k):
    """
    Use pre-computed verticality from CloudCompare if available,
    otherwise compute it from scratch.

    CloudCompare saves verticality as an extra dimension whose name starts
    with 'Verticality' or 'verticality' (case-insensitive), e.g.
    'Verticality (0.05)'. We search for any field matching that prefix
    and ignore the radius suffix so different tiles can use different radii.
    """
    dims = [d.name for d in las.point_format.dimensions]
    extra_dims = ([d.name for d in las.point_format.extra_dims]
                  if hasattr(las.point_format, 'extra_dims') else [])
    all_dims = dims + extra_dims

    vert_field = None
    for name in all_dims:
        if name.lower().startswith('verticality'):
            vert_field = name
            break

    if vert_field is not None:
        print(f"  Using pre-computed verticality field: '{vert_field}'")
        vert = np.array(las[vert_field], dtype=np.float32)
        vert = np.nan_to_num(vert, nan=0.0)
        vert = np.clip(vert, 0.0, 1.0)
    else:
        print("  No pre-computed verticality found — computing from scratch...")
        vert = compute_verticality(x, y, z, k=k)

    return vert


def process_tile(laz_path, model, device, resolution, k, patch_size,
                 inference_stride, output_dir):
    tile_name = Path(laz_path).stem
    print(f"\n{'='*60}\nProcessing: {tile_name}")

    las = load_laz(laz_path)
    x, y, z, intensity, rgb = get_arrays(las)
    print(f"  Points: {len(x):,}")

    vert = get_or_compute_verticality(las, x, y, z, k=k)
    print("  Computing height above ground...")
    hag  = compute_height_above_ground(x, y, z)

    print("  Rasterizing...")
    raster, winner, point_pixel_map, meta = build_raster(
        x, y, z, intensity, rgb, vert, hag, resolution)
    rows, cols = raster.shape[0], raster.shape[1]
    print(f"  Raster: {rows}×{cols} px")

    pred_label_map = run_sliding_inference(
        model, raster, patch_size, inference_stride, device)

    labels = backproject_to_3d(pred_label_map, winner, point_pixel_map, x, y, z, cols)

    # Write segmented LAZ
    header = laspy.LasHeader(
    point_format=las.header.point_format.id,
    version=las.header.version
)
    header.offsets = las.header.offsets
    header.scales  = las.header.scales

    try:
        crs = las.header.parse_crs()
        if crs is not None:
            header.set_crs(crs)
    except Exception as e:
        print(f"  WARNING: could not set CRS — {e}")
    clean_las = laspy.LasData(header=header)
    clean_las.x              = las.x
    clean_las.y              = las.y
    clean_las.z              = las.z
    clean_las.intensity      = las.intensity
    clean_las.classification = labels
    if hasattr(las, 'red'):
        clean_las.red   = las.red
        clean_las.green = las.green
        clean_las.blue  = las.blue
    if hasattr(las, 'return_number'):
        clean_las.return_number     = las.return_number
        clean_las.number_of_returns = las.number_of_returns

    out_laz_path = Path(output_dir) / f"{tile_name}_segmented.laz"
    clean_las.write(str(out_laz_path))
    print(f"  Saved segmented LAZ: {out_laz_path}")

    # Save visualizations
    save_visualizations(raster, pred_label_map, output_dir, tile_name)

    # Quick class distribution report
    unique, counts = np.unique(labels, return_counts=True)
    label_names = {0: "unlabeled", 1: "ground", 2: "road"}
    print(f"  Predicted class distribution:")
    for u, c in zip(unique, counts):
        print(f"    [{u}] {label_names.get(int(u), str(u)):<10} {c:>10,}  ({100*c/len(labels):5.1f}%)")


# ─── Main ──────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Run inference with a trained curb-gutter SegFormer")
    parser.add_argument("--model_folder", required=True,
                        help="Run folder containing config.json + best.pt (created by train_segformer.py)")
    parser.add_argument("--input_folder", default=None,
                        help="Folder of unlabeled .laz files (overrides config.json inference_config)")
    parser.add_argument("--single_file",  default=None,
                        help="Path to one .laz file (overrides config.json inference_config)")
    parser.add_argument("--output_folder", default=None,
                        help="Where to save segmented LAZ + visualizations (overrides config.json)")
    parser.add_argument("--checkpoint", default="last.pt", choices=["best.pt", "last.pt"],
                        help="Which checkpoint in model_folder to load (default: best.pt)")
    args = parser.parse_args()

    model_folder = Path(args.model_folder)
    config_path = model_folder / "config.json"
    if not config_path.exists():
        print(f"ERROR: {config_path} not found. Was this run trained with the updated "
              f"train_segformer.py that auto-generates config.json?")
        sys.exit(1)

    with open(config_path) as f:
        full_config = json.load(f)

    tc = full_config["training_config"]
    ic = full_config["inference_config"]

    print(f"Loaded config for run: {tc['run_name']}")
    print(f"  model_size={tc['model_size']} | resolution={tc['resolution']}m | "
          f"k={tc['k_neighbors']} | patch_size={tc['patch_size']}")

    # CLI args override config.json inference_config, but config.json is the fallback —
    # this lets you either edit the file by hand or pass quick one-off CLI overrides.
    input_folder  = args.input_folder  if args.input_folder  is not None else ic.get("input_folder")
    single_file   = args.single_file   if args.single_file   is not None else ic.get("single_file")
    output_folder = args.output_folder if args.output_folder is not None else ic.get("output_folder")
    inference_stride = ic.get("inference_stride", 256)

    run_option = "single" if single_file else "folder"
    if args.single_file:
        run_option = "single"
    elif args.input_folder:
        run_option = "folder"
    else:
        run_option = ic.get("run_option", "folder")

    if not output_folder:
        print("ERROR: No output_folder specified via --output_folder or config.json inference_config.")
        sys.exit(1)

    Path(output_folder).mkdir(parents=True, exist_ok=True)

    if run_option == "single":
        if not single_file:
            print("ERROR: run_option is 'single' but no single_file path was provided "
                  "(via --single_file or config.json inference_config.single_file).")
            sys.exit(1)
        laz_files = [Path(single_file)]
    else:
        if not input_folder:
            print("ERROR: run_option is 'folder' but no input_folder path was provided "
                  "(via --input_folder or config.json inference_config.input_folder).")
            sys.exit(1)
        input_dir = Path(input_folder)
        laz_files = sorted(list(input_dir.glob("*.laz")) + list(input_dir.glob("*.las")) +
                           list(input_dir.glob("*.LAZ")) + list(input_dir.glob("*.LAS")))
        if not laz_files:
            print(f"ERROR: No .laz/.las files found in {input_dir}")
            sys.exit(1)

    print(f"Run option: {run_option} | Tiles to process: {len(laz_files)}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Build model with the EXACT same function training used, then load weights
    model = build_model(
        model_size=tc["model_size"],
        num_channels=tc["num_channels"],
        num_labels=tc["num_labels"],
    )
    checkpoint_path = model_folder / args.checkpoint
    if not checkpoint_path.exists():
        print(f"ERROR: checkpoint not found at {checkpoint_path}")
        sys.exit(1)

    ckpt = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(device)
    model.eval()
    print(f"Loaded checkpoint: {checkpoint_path} (epoch={ckpt.get('epoch')}, "
          f"val_iou={ckpt.get('val_iou', ckpt.get('best_iou')):.4f})")

    patch_size = tc["patch_size"]
    if patch_size is None:
        print("ERROR: config.json has patch_size=null. This run's config.json was generated "
              "before the patch-size auto-detection fix — re-train or manually set "
              "training_config.patch_size in config.json before running inference.")
        sys.exit(1)

    for laz_path in laz_files:
        try:
            process_tile(
                laz_path, model, device,
                resolution=tc["resolution"],
                k=tc["k_neighbors"],
                patch_size=patch_size,
                inference_stride=inference_stride,
                output_dir=output_folder,
            )
        except Exception as e:
            print(f"  ERROR processing {laz_path.name}: {e}")
            import traceback; traceback.print_exc()
            continue

    print(f"\nDone. Segmented LAZ files + visualizations saved to: {output_folder}")


if __name__ == "__main__":
    main()